"""
app/services/export_service.py — PDF export with ReportLab.
"""
from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_NAVY = colors.HexColor("#0D1B2A")
_GOLD = colors.HexColor("#C9993F")
_TEAL = colors.HexColor("#0F3D3E")
_WHITE = colors.white
_LIGHT = colors.HexColor("#F8F9FA")


def _styles():
    base = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "NMTitle",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=_GOLD,
        spaceAfter=8,
    )
    h2_style = ParagraphStyle(
        "NMH2",
        parent=base["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=_NAVY,
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "NMBody",
        parent=base["Normal"],
        fontSize=10,
        spaceAfter=4,
        leading=14,
    )
    return title_style, h2_style, body_style


class ExportService:

    async def export_prediction(self, prediction: dict) -> bytes:
        """A4 PDF: case details, outcome badge, confidence breakdown, top features."""
        buf  = io.BytesIO()
        doc  = SimpleDocTemplate(buf, pagesize=A4,
                                  leftMargin=2*cm, rightMargin=2*cm,
                                  topMargin=2*cm, bottomMargin=2*cm)
        title_s, h2_s, body_s = _styles()
        story = []

        # Header
        story.append(Paragraph("NyayMarg — Prediction Report", title_s))
        story.append(HRFlowable(width="100%", thickness=2, color=_GOLD))
        story.append(Spacer(1, 10))

        # Outcome badge row
        outcome = prediction.get("predicted_outcome", "—")
        conf    = prediction.get("ensemble_confidence", 0)
        outcome_color = colors.HexColor("#28A745") if outcome == "Allowed" else colors.HexColor("#DC3545")

        meta_data = [
            ["Predicted Outcome", outcome],
            ["Ensemble Confidence", f"{conf * 100:.1f}%"],
            ["RFC Confidence",    f"{prediction.get('rfc_confidence', 0) * 100:.1f}%"],
            ["LogReg Confidence", f"{prediction.get('logreg_confidence', 0) * 100:.1f}%"],
            ["Generated At",      datetime.utcnow().strftime("%d %b %Y %H:%M UTC")],
        ]
        t = Table(meta_data, colWidths=[6*cm, 10*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (0, -1), _TEAL),
            ("TEXTCOLOR",   (0, 0), (0, -1), _LIGHT),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F8F8F8"), _WHITE]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("PADDING",     (0, 0), (-1, -1), 6),
            ("TEXTCOLOR",   (1, 0), (1, 0), outcome_color),
            ("FONTNAME",    (1, 0), (1, 0), "Helvetica-Bold"),
        ]))
        story.append(t)
        story.append(Spacer(1, 16))

        # Top features
        feats = prediction.get("top_features", [])
        if feats:
            story.append(Paragraph("Key Contributing Factors", h2_s))
            feat_data = [["Feature", "Importance"]] + [
                [f["feature"], f"{f['importance']:.4f}"] for f in feats
            ]
            ft = Table(feat_data, colWidths=[10*cm, 6*cm])
            ft.setStyle(TableStyle([
                ("BACKGROUND",  (0, 0), (-1, 0), _NAVY),
                ("TEXTCOLOR",   (0, 0), (-1, 0), _GOLD),
                ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE",    (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F8F8F8"), _WHITE]),
                ("GRID",        (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("PADDING",     (0, 0), (-1, -1), 6),
            ]))
            story.append(ft)

        story.append(Spacer(1, 20))
        story.append(Paragraph(
            "This report was generated by NyayMarg v2.0 — AI-Powered Legal Analytics",
            ParagraphStyle("Footer", fontSize=8, textColor=colors.grey),
        ))

        doc.build(story)
        return buf.getvalue()

    async def export_analytics(self, data: dict) -> bytes:
        """Multi-page PDF with analytics overview."""
        buf  = io.BytesIO()
        doc  = SimpleDocTemplate(buf, pagesize=A4,
                                  leftMargin=2*cm, rightMargin=2*cm,
                                  topMargin=2*cm, bottomMargin=2*cm)
        title_s, h2_s, body_s = _styles()
        story = []

        story.append(Paragraph("NyayMarg — Analytics Report", title_s))
        story.append(HRFlowable(width="100%", thickness=2, color=_GOLD))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            f"Generated: {datetime.utcnow().strftime('%d %b %Y %H:%M UTC')}", body_s
        ))
        story.append(Spacer(1, 16))

        # Overview table
        story.append(Paragraph("Platform Overview", h2_s))
        ov = data.get("overview", {})
        rows = [["Metric", "Value"]] + [[k.replace("_", " ").title(), str(v)] for k, v in ov.items()]
        t = Table(rows, colWidths=[9*cm, 7*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR",   (0, 0), (-1, 0), _GOLD),
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F8F8F8"), _WHITE]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("PADDING",     (0, 0), (-1, -1), 6),
        ]))
        story.append(t)

        doc.build(story)
        return buf.getvalue()
